export const matches = [
	{
		id: 1,
		leftTeam: 'Qatar',
		rightTeam: 'Ekwador',
		leftScore: 0,
		rightScore: 0,
		leftFlag: 'QA',
		rightFlag: 'EC',
	},
	{
		id: 2,
		leftTeam: 'Anglia',
		rightTeam: 'Iran',
		leftScore: 0,
		rightScore: 0,
		leftFlag: 'GB',
		rightFlag: 'IR',
	},
	{
		id: 3,
		leftTeam: 'Senegal',
		rightTeam: 'Holandia',
		leftScore: 0,
		rightScore: 0,
		leftFlag: 'SN',
		rightFlag: 'NL',
	},
	{
		id: 4,
		leftTeam: 'USA',
		rightTeam: 'Walia',
		leftScore: 0,
		rightScore: 0,
		leftFlag: 'US',
		rightFlag: 'WL',
	},
	{
		id: 5,
		leftTeam: 'Argentyna',
		rightTeam: 'Arabia Saudyjska',
		leftScore: 0,
		rightScore: 0,
		leftFlag: 'AR',
		rightFlag: 'SA',
	},
	{
		id: 6,
		leftTeam: 'Dania',
		rightTeam: 'Tunezja',
		leftScore: 0,
		rightScore: 0,
		leftFlag: 'DK',
		rightFlag: 'TN',
	},
	{
		id: 7,
		leftTeam: 'Meksyk',
		rightTeam: 'Polska',
		leftScore: 0,
		rightScore: 0,
		leftFlag: 'MX',
		rightFlag: 'PL',
	},
];
