export const matches = [
	// [
	// 	{
	// 		id: 1,
	// 		leftTeam: 'Qatar',
	// 		rightTeam: 'Ekwador',
	// 		leftFlag: 'QA',
	// 		rightFlag: 'EC',
	// 		date: 'Faza Grupowa - Ndz, 20.11',
	// 		dateTime: '2022-11-20T16:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 2,
	// 		leftTeam: 'Anglia',
	// 		rightTeam: 'Iran',
	// 		leftFlag: 'GB',
	// 		rightFlag: 'IR',
	// 		date: 'Faza Grupowa - Pon, 21.11',
	// 		dateTime: '2022-11-21T16:00:00',
	// 	},
	// 	{
	// 		id: 3,
	// 		leftTeam: 'Senegal',
	// 		rightTeam: 'Holandia',
	// 		leftFlag: 'SN',
	// 		rightFlag: 'NL',
	// 		date: 'Faza Grupowa - Pon, 21.11',
	// 		dateTime: '2022-11-21T16:00:00',
	// 	},
	// 	{
	// 		id: 4,
	// 		leftTeam: 'USA',
	// 		rightTeam: 'Walia',
	// 		leftFlag: 'US',
	// 		rightFlag: 'GB_WLS',
	// 		date: 'Faza Grupowa - Pon, 21.11',
	// 		dateTime: '2022-11-21T16:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 5,
	// 		leftTeam: 'Argentyna',
	// 		rightTeam: 'Arabia Saudyjska',
	// 		leftFlag: 'AR',
	// 		rightFlag: 'SA',
	// 		date: 'Faza Grupowa - Pon, 21.11',
	// 		dateTime: '2022-11-21T16:00:00',
	// 	},
	// 	{
	// 		id: 6,
	// 		leftTeam: 'Dania',
	// 		rightTeam: 'Tunezja',
	// 		leftFlag: 'DK',
	// 		rightFlag: 'TN',
	// 		date: 'Faza Grupowa - Wt, 22.11',
	// 		dateTime: '2022-11-22T11:00:00',
	// 	},
	// 	{
	// 		id: 7,
	// 		leftTeam: 'Meksyk',
	// 		rightTeam: 'Polska',
	// 		leftFlag: 'MX',
	// 		rightFlag: 'PL',
	// 		date: 'Faza Grupowa - Wt, 22.11',
	// 		dateTime: '2022-11-22T11:00:00',
	// 	},
	// 	{
	// 		id: 8,
	// 		leftTeam: 'Francja',
	// 		rightTeam: 'Australia',
	// 		leftFlag: 'FR',
	// 		rightFlag: 'AU',
	// 		date: 'Faza Grupowa - Wt, 22.11',
	// 		dateTime: '2022-11-22T11:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 9,
	// 		leftTeam: 'Maroko',
	// 		rightTeam: 'Chorwacja',
	// 		leftFlag: 'MA',
	// 		rightFlag: 'HR',
	// 		date: 'Faza Grupowa - Sr, 23.11',
	// 		dateTime: '2022-11-23T10:00:00',
	// 	},
	// 	{
	// 		id: 10,
	// 		leftTeam: 'Niemcy',
	// 		rightTeam: 'Japonia',
	// 		leftFlag: 'DE',
	// 		rightFlag: 'JP',
	// 		date: 'Faza Grupowa - Sr, 23.11',
	// 		dateTime: '2022-11-23T10:00:00',
	// 	},
	// 	{
	// 		id: 11,
	// 		leftTeam: 'Hiszpania',
	// 		rightTeam: 'Kostaryka',
	// 		leftFlag: 'ES',
	// 		rightFlag: 'CR',
	// 		date: 'Faza Grupowa - Sr, 23.11',
	// 		dateTime: '2022-11-23T10:00:00',
	// 	},
	// 	{
	// 		id: 12,
	// 		leftTeam: 'Belgia',
	// 		rightTeam: 'Kanada',
	// 		leftFlag: 'BE',
	// 		rightFlag: 'CA',
	// 		date: 'Faza Grupowa - Sr, 23.11',
	// 		dateTime: '2022-11-23T10:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 13,
	// 		leftTeam: 'Szwajcaria',
	// 		rightTeam: 'Kamerun',
	// 		leftFlag: 'CH',
	// 		rightFlag: 'CM',
	// 		date: 'Faza Grupowa - Czwt, 24.11',
	// 		dateTime: '2022-11-24T10:00:00',
	// 	},
	// 	{
	// 		id: 14,
	// 		leftTeam: 'Urugwaj',
	// 		rightTeam: 'Korea Południowa',
	// 		leftFlag: 'UY',
	// 		rightFlag: 'KR',
	// 		date: 'Faza Grupowa - Czwt, 24.11',
	// 		dateTime: '2022-11-24T10:00:00',
	// 	},
	// 	{
	// 		id: 15,
	// 		leftTeam: 'Portugalia',
	// 		rightTeam: 'Ghana',
	// 		leftFlag: 'PT',
	// 		rightFlag: 'GH',
	// 		date: 'Faza Grupowa - Czwt, 24.11',
	// 		dateTime: '2022-11-24T10:00:00',
	// 	},
	// 	{
	// 		id: 16,
	// 		leftTeam: 'Brazilia',
	// 		rightTeam: 'Serbia',
	// 		leftFlag: 'BR',
	// 		rightFlag: 'RS',
	// 		date: 'Faza Grupowa - Czwt, 24.11',
	// 		dateTime: '2022-11-24T10:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 17,
	// 		leftTeam: 'Walia',
	// 		rightTeam: 'Iran',
	// 		leftFlag: 'GB_WLS',
	// 		rightFlag: 'IR',
	// 		date: 'Faza Grupowa - Pt, 25.11',
	// 		dateTime: '2022-11-25T10:00:00',
	// 	},
	// 	{
	// 		id: 18,
	// 		leftTeam: 'Katar',
	// 		rightTeam: 'Senegal',
	// 		leftFlag: 'QA',
	// 		rightFlag: 'SN',
	// 		date: 'Faza Grupowa - Pt, 25.11',
	// 		dateTime: '2022-11-25T10:00:00',
	// 	},
	// 	{
	// 		id: 19,
	// 		leftTeam: 'Holandia',
	// 		rightTeam: 'Ekwador',
	// 		leftFlag: 'NL',
	// 		rightFlag: 'EC',
	// 		date: 'Faza Grupowa - Pt, 25.11',
	// 		dateTime: '2022-11-25T10:00:00',
	// 	},
	// 	{
	// 		id: 20,
	// 		leftTeam: 'Anglia',
	// 		rightTeam: 'USA',
	// 		leftFlag: 'GB',
	// 		rightFlag: 'US',
	// 		date: 'Faza Grupowa - Pt, 25.11',
	// 		dateTime: '2022-11-25T10:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 21,
	// 		leftTeam: 'Tunezja',
	// 		rightTeam: 'Australia',
	// 		leftFlag: 'TN',
	// 		rightFlag: 'AU',
	// 		date: 'Faza Grupowa - Sob, 26.11',
	// 		dateTime: '2022-11-26T10:00:00',
	// 	},
	// 	{
	// 		id: 22,
	// 		leftTeam: 'Polska',
	// 		rightTeam: 'Arabia Saudyjska',
	// 		leftFlag: 'PL',
	// 		rightFlag: 'SA',
	// 		date: 'Faza Grupowa - Sob, 26.11',
	// 		dateTime: '2022-11-26T10:00:00',
	// 	},
	// 	{
	// 		id: 23,
	// 		leftTeam: 'Francja',
	// 		rightTeam: 'Dania',
	// 		leftFlag: 'FR',
	// 		rightFlag: 'DK',
	// 		date: 'Faza Grupowa - Sob, 26.11',
	// 		dateTime: '2022-11-26T10:00:00',
	// 	},
	// 	{
	// 		id: 24,
	// 		leftTeam: 'Argentyna',
	// 		rightTeam: 'Meksyk',
	// 		leftFlag: 'AR',
	// 		rightFlag: 'MX',
	// 		date: 'Faza Grupowa - Sob, 26.11',
	// 		dateTime: '2022-11-26T10:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 25,
	// 		leftTeam: 'Japonia',
	// 		rightTeam: 'Kostaryka',
	// 		leftFlag: 'JP',
	// 		rightFlag: 'CR',
	// 		date: 'Faza Grupowa - Ndz, 27.11',
	// 		dateTime: '2022-11-27T10:00:00',
	// 	},
	// 	{
	// 		id: 26,
	// 		leftTeam: 'Belgia',
	// 		rightTeam: 'Maroko',
	// 		leftFlag: 'BE',
	// 		rightFlag: 'MA',
	// 		date: 'Faza Grupowa - Ndz, 27.11',
	// 		dateTime: '2022-11-27T10:00:00',
	// 	},
	// 	{
	// 		id: 27,
	// 		leftTeam: 'Chorwacja',
	// 		rightTeam: 'Kanaada',
	// 		leftFlag: 'HR',
	// 		rightFlag: 'CA',
	// 		date: 'Faza Grupowa - Ndz, 27.11',
	// 		dateTime: '2022-11-27T10:00:00',
	// 	},
	// 	{
	// 		id: 28,
	// 		leftTeam: 'Hiszpania',
	// 		rightTeam: 'Niemcy',
	// 		leftFlag: 'ES',
	// 		rightFlag: 'DE',
	// 		date: 'Faza Grupowa - Ndz, 27.11',
	// 		dateTime: '2022-11-27T10:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 29,
	// 		leftTeam: 'Kamerun',
	// 		rightTeam: 'Serbia',
	// 		leftFlag: 'CM',
	// 		rightFlag: 'RS',
	// 		date: 'Faza Grupowa - Pon, 28.11',
	// 		dateTime: '2022-11-28T10:00:00',
	// 	},
	// 	{
	// 		id: 30,
	// 		leftTeam: 'Korea Południowa',
	// 		rightTeam: 'Ghana',
	// 		leftFlag: 'KR',
	// 		rightFlag: 'GH',
	// 		date: 'Faza Grupowa - Pon, 28.11',
	// 		dateTime: '2022-11-28T10:00:00',
	// 	},
	// 	{
	// 		id: 31,
	// 		leftTeam: 'Brazylia',
	// 		rightTeam: 'Szwajcaria',
	// 		leftFlag: 'BR',
	// 		rightFlag: 'CH',
	// 		date: 'Faza Grupowa - Pon, 28.11',
	// 		dateTime: '2022-11-28T10:00:00',
	// 	},
	// 	{
	// 		id: 32,
	// 		leftTeam: 'Portugalia',
	// 		rightTeam: 'Urugwaj',
	// 		leftFlag: 'PT',
	// 		rightFlag: 'UY',
	// 		date: 'Faza Grupowa - Pon, 28.11',
	// 		dateTime: '2022-11-28T10:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 33,
	// 		leftTeam: 'Ekwador',
	// 		rightTeam: 'Senegal',
	// 		leftFlag: 'EC',
	// 		rightFlag: 'SN',
	// 		date: 'Faza Grupowa - Wt, 29.11',
	// 		dateTime: '2022-11-29T15:00:00',
	// 	},
	// 	{
	// 		id: 34,
	// 		leftTeam: 'Holandia',
	// 		rightTeam: 'Katar',
	// 		leftFlag: 'NL',
	// 		rightFlag: 'QA',
	// 		date: 'Faza Grupowa - Wt, 29.11',
	// 		dateTime: '2022-11-29T15:00:00',
	// 	},
	// 	{
	// 		id: 35,
	// 		leftTeam: 'Iran',
	// 		rightTeam: 'USA',
	// 		leftFlag: 'IR',
	// 		rightFlag: 'US',
	// 		date: 'Faza Grupowa - Wt, 29.11',
	// 		dateTime: '2022-11-29T15:00:00',
	// 	},
	// 	{
	// 		id: 36,
	// 		leftTeam: 'Walia',
	// 		rightTeam: 'Anglia',
	// 		leftFlag: 'GB_WLS',
	// 		rightFlag: 'GB',
	// 		date: 'Faza Grupowa - Wt, 29.11',
	// 		dateTime: '2022-11-29T15:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 37,
	// 		leftTeam: 'Tunezja',
	// 		rightTeam: 'Francja',
	// 		leftFlag: 'TN',
	// 		rightFlag: 'FR',
	// 		date: 'Faza Grupowa - Sr, 30.11',
	// 		dateTime: '2022-11-30T15:00:00',
	// 	},
	// 	{
	// 		id: 38,
	// 		leftTeam: 'Australia',
	// 		rightTeam: 'Dania',
	// 		leftFlag: 'AU',
	// 		rightFlag: 'DK',
	// 		date: 'Faza Grupowa - Sr, 30.11',
	// 		dateTime: '2022-11-30T15:00:00',
	// 	},
	// 	{
	// 		id: 39,
	// 		leftTeam: 'Polska',
	// 		rightTeam: 'Argentyna',
	// 		leftFlag: 'PL',
	// 		rightFlag: 'AR',
	// 		date: 'Faza Grupowa - Sr, 30.11',
	// 		dateTime: '2022-11-30T15:00:00',
	// 	},
	// 	{
	// 		id: 40,
	// 		leftTeam: 'Arabia Saudyjska',
	// 		rightTeam: 'Meksyk',
	// 		leftFlag: 'SA',
	// 		rightFlag: 'MX',
	// 		date: 'Faza Grupowa - Sr, 30.11',
	// 		dateTime: '2022-11-30T15:00:00',
	// 	},
	// ],
	// [
	// 	{
	// 		id: 41,
	// 		leftTeam: 'Chorwacja',
	// 		rightTeam: 'Belgia',
	// 		leftFlag: 'HR',
	// 		rightFlag: 'BE',
	// 		date: 'Faza Grupowa - Czw, 01.12',
	// 		dateTime: '2022-12-01T15:00:00',
	// 	},
	// 	{
	// 		id: 42,
	// 		leftTeam: 'Kanaada',
	// 		rightTeam: 'Maroko',
	// 		leftFlag: 'CA',
	// 		rightFlag: 'MA',
	// 		date: 'Faza Grupowa - Czw, 01.12',
	// 		dateTime: '2022-12-01T15:00:00',
	// 	},
	// 	{
	// 		id: 43,
	// 		leftTeam: 'Japonia',
	// 		rightTeam: 'Hiszpania',
	// 		leftFlag: 'JP',
	// 		rightFlag: 'ES',
	// 		date: 'Faza Grupowa - Czw, 01.12',
	// 		dateTime: '2022-12-01T15:00:00',
	// 	},
	// 	{
	// 		id: 44,
	// 		leftTeam: 'Kostaryka',
	// 		rightTeam: 'Niemcy',
	// 		leftFlag: 'CR',
	// 		rightFlag: 'DE',
	// 		date: 'Faza Grupowa - Czw, 01.12',
	// 		dateTime: '2022-12-01T15:00:00',
	// 	},
	// ],
	[
		{
			id: 45,
			leftTeam: 'Korea Południowa',
			rightTeam: 'Portugalia',
			leftFlag: 'KR',
			rightFlag: 'PT',
			date: 'Faza Grupowa - Pt, 02.12',
			dateTime: '2022-12-02T15:00:00',
		},
		{
			id: 46,
			leftTeam: 'Ghana',
			rightTeam: 'Urugwaj',
			leftFlag: 'GH',
			rightFlag: 'UY',
			date: 'Faza Grupowa - Pt, 02.12',
			dateTime: '2022-12-02T15:00:00',
		},
		{
			id: 47,
			leftTeam: 'Serbia',
			rightTeam: 'Szwajcaria',
			leftFlag: 'RS',
			rightFlag: 'CH',
			date: 'Faza Grupowa - Pt, 02.12',
			dateTime: '2022-12-02T15:00:00',
		},
		{
			id: 48,
			leftTeam: 'Kamerun',
			rightTeam: 'Brazylia',
			leftFlag: 'CM',
			rightFlag: 'BR',
			date: 'Faza Grupowa - Pt, 02.12',
			dateTime: '2022-12-02T15:00:00',
		},
	],
	[
		{
			id: 49,
			leftTeam: 'Holandia',
			rightTeam: 'USA',
			leftFlag: 'NL',
			rightFlag: 'US',
			date: 'Sob, 03.12',
			dateTime: '2022-12-03T15:00:00',
		},
		{
			id: 50,
			leftTeam: 'Arentyna',
			rightTeam: 'Australia',
			leftFlag: 'AR',
			rightFlag: 'AU',
			date: 'Sob, 03.12',
			dateTime: '2022-12-03T15:00:00',
		},
	],
	[
		{
			id: 51,
			leftTeam: 'Francja',
			rightTeam: 'Polska',
			leftFlag: 'FR',
			rightFlag: 'PL',
			date: 'Ndz, 04.12',
			dateTime: '2022-12-04T15:00:00',
		},
		{
			id: 52,
			leftTeam: 'Anglia',
			rightTeam: 'Senegal',
			leftFlag: 'GB',
			rightFlag: 'SN',
			date: 'Ndz, 04.12',
			dateTime: '2022-12-04T15:00:00',
		},
	],
	[
		{
			id: 53,
			leftTeam: 'Japonia',
			rightTeam: 'Chorwacja',
			leftFlag: 'JP',
			rightFlag: 'HR',
			date: 'Pon, 05.12',
			dateTime: '2022-12-05T15:00:00',
		},
		{
			id: 54,
			leftTeam: 'TBA',
			rightTeam: 'Korea Południowa',
			leftFlag: '',
			rightFlag: 'KR',
			date: 'Pon, 05.12',
			dateTime: '2022-12-05T15:00:00',
		},
	],
	[
		{
			id: 55,
			leftTeam: 'Maroko',
			rightTeam: 'Hiszpania',
			leftFlag: 'MA',
			rightFlag: 'ES',
			date: 'Wt, 06.12',
			dateTime: '2022-12-06T15:00:00',
		},
		{
			id: 56,
			leftTeam: 'Portugalia',
			rightTeam: 'TBA',
			leftFlag: 'PT',
			rightFlag: '',
			date: 'Wt, 06.12',
			dateTime: '2022-12-06T15:00:00',
		},
	],
];
